name: Build Docker image

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-docker-image.yml'
      - 'files/**'
      - 'mu-plugins/**'
      - 'composer.*'
      - 'Dockerfile'
      - 'wp-config.php'

env:
  IMAGE: ghcr.io/druidfi/bazooka-wordpress

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:build-${{ github.run_number }}
            ${{ env.IMAGE }}:${{ steps.date.outputs.date }}.${{ github.run_number }}
