name: Build Docker image

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-docker-image.yml'
      - 'files/**'
      - 'mu-plugins/**'
      - 'composer.*'
      - 'Dockerfile'
      - 'wp-config.php'

env:
  DB_HOST: 127.0.0.1
  DB_NAME: wordpress
  DB_USER: root
  DB_PASSWORD: root
  IMAGE: ghcr.io/druidfi/bazooka-wordpress

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Start MySQL and create wordpress database
        run: |
          sudo systemctl start mysql.service
          mysql -u${{ env.DB_USER }} -e "create database ${{ env.DB_NAME }}";
        env:
          MYSQL_PWD: ${{ env.DB_PASSWORD }}

      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          load: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:build-${{ github.run_number }}
            ${{ env.IMAGE }}:${{ steps.date.outputs.date }}.${{ github.run_number }}

      - name: Test
        run: |
          docker run --rm --detach -p 80:8080 \
            --env DB_HOST=${{ env.DB_HOST }} --env DB_NAME=${{ env.DB_NAME }} \
            --env DB_USER=${{ env.DB_USER }} --env DB_PASS=${{ env.DB_PASS }} \
            ${{ env.IMAGE }}:latest

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:build-${{ github.run_number }}
            ${{ env.IMAGE }}:${{ steps.date.outputs.date }}.${{ github.run_number }}
